# Generated by Django 3.2.8 on 2021-11-24 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=40, verbose_name='Endereço')),
                ('cep', models.CharField(max_length=7, verbose_name='CEP')),
                ('metros', models.FloatField(verbose_name='Metros')),
                ('dormitorios', models.IntegerField(verbose_name='Dormitórios')),
                ('banheiros', models.IntegerField(verbose_name='Banheiros')),
                ('garagem', models.CharField(max_length=1, verbose_name='Garagem')),
                ('vagas_garagem', models.IntegerField(verbose_name='Vagas na Garagem')),
                ('varanda', models.CharField(max_length=1, verbose_name='Varanda')),
                ('data_inclusao', models.DateTimeField(auto_now=True, verbose_name='Data Inclusao')),
                ('tipo_contrato', models.CharField(choices=[('A', 'Aluguel'), ('V', 'Venda')], max_length=1, verbose_name='Tipo Contrato')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condicao', models.CharField(choices=[('U', 'Usado'), ('N', 'Novo')], max_length=1, verbose_name='Condição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imovel',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=20)),
                ('telefone', models.CharField(max_length=9)),
                ('data_nascimento', models.DateTimeField(verbose_name='Data de Nascimento')),
                ('data_cadastro', models.DateTimeField(auto_now=True, verbose_name='Data Cadastrado')),
                ('imovel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.imovel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
