# Generated by Django 3.2.8 on 2021-11-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images', verbose_name='Imagem 6'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images', verbose_name='Imagem 1'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images', verbose_name='Imagem 2'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images', verbose_name='Imagem 3'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images', verbose_name='Imagem 4'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images', verbose_name='Imagem 5'),
        ),
    ]
